### ISSUE TITLE
Audiobook inventory is parsed and added incorrectly

### ISSUE THREAD

**Issue by kevinclevenger** [Goodwy/PlayBooks#1]
Given a directory structure like 
../Author Name
    |- Book A
    |- Book B

PlayBooks presents them in the books inventory list as 
  Author Name
    |- Book A 

Select Book A and in the chapters will be Book A (part 1-35) Book B (part 36-58). So it appears to the user as if Book B wasn't found at all until Book A is selected and the chapters are checked.

The behavior is also seen after resetting and re-writing all meta tags on all files in all books. 

For example setting only:
Album: Book A
Performer: Author Name
on all files in Audiobooks/Author Name/Book A, and setting only:
Album: Book B
Performer: Author Name
on all files in Audiobooks/Author Name/Book B, and no other explicitly tags, PlayBooks still lists the inventory as Author Name>BookA (part 1-35) Book B (part 36-58)

**Comment by Goodwy** [comment]
Books can now be added in two ways:
1. By specifying a specific directory, then all files in it will be considered one book.
2. By specifying a directory in which there are many books, then each directory inside will be considered a separate book.

In your case, in order to correctly identify the books, you can either specify each book separately according to the first option, or specify the directory of each author according to the second option.

In the future I will try to add the ability to specify directories according to your option.

**Comment by ShawnPConroy** [comment]
I have an additional option, but this might be too complex to pull off quickly:

Simple organize the audiobook inventory by author name-title metadata. This way it doesn't matter where the files are at all. Have this be the default 'Smart Scan'. For people where it doesn't work, rather than adding a smart scan folder for well documented metadata files, they can choose the 'folder per book' or 'single book location'.

The folder per book option is pretty much what you have now. But it should treat subfolders as separate folders. Just create a new book in your index for each individual folder, since nothing is in the author folder. Or genre folder. Or whatever that folder is. I don't know the code and don't know what solution you are working on, but looking at each folder recursively, or seeing the file list and parsing on slashes might be an easier workaround? I'm just surprised the current method pulls all files in one folder and sub-folder and adds them as the same book, rather than folder by folder.

Alternatively, you could make it so if it detects sub-folders (with audio files) in any folder, it simply adds them as their own location? The problem is when those folders are deleted.

Just some options, most of which are probably not applicable to the code base you are working with. I love the work you have been doing updating this app for the last year. It's come a long way. And for most people, including myself, I suspect this feature works just fine as is.

**Comment by Goodwy** [comment]
In version 1.1.4, a new button has been added to add a folder with subfolders. This should be fine for those who have books sorted into subfolders.
